In [1]:
import numpy as np

In [2]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(1,101,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [10]:
np.arange(3,22,3)

array([ 3,  6,  9, 12, 15, 18, 21])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [23]:
np.random.rand(3,5)

array([[0.56318699, 0.34207659, 0.98807396, 0.06075226, 0.76770137],
       [0.55518346, 0.72974984, 0.72982772, 0.82881577, 0.74136125],
       [0.2335056 , 0.4595007 , 0.41253468, 0.68610619, 0.10207436]])

In [25]:
np.random.randn(3,5)

array([[-0.27515096,  0.30925215,  0.16490472,  0.9699258 ,  0.69302377],
       [ 1.68432205,  2.37119189,  2.27828588,  0.16740967, -0.44813043],
       [ 0.17037012, -1.69101832,  0.4951743 , -0.74511621,  1.22909522]])

In [27]:
np.random.randint(0,10,50)

array([0, 4, 3, 0, 0, 5, 7, 6, 6, 2, 6, 8, 8, 0, 6, 1, 7, 9, 0, 7, 7, 9,
       1, 4, 8, 2, 3, 5, 0, 6, 7, 8, 8, 6, 0, 5, 0, 3, 5, 7, 7, 6, 4, 9,
       2, 3, 3, 0, 3, 3])

In [29]:
sample_array=np.arange(0,30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
sample_array.reshape(10,6)

ValueError: cannot reshape array of size 30 into shape (10,6)

In [32]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
sample_array[6]

6

In [35]:
sample_array[60]

IndexError: index 60 is out of bounds for axis 0 with size 30

In [36]:
sample_array[5:10]

array([5, 6, 7, 8, 9])

In [37]:
sample_array[0]=100

In [38]:
sample_array

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [41]:
sample_matrix=np.array([[1,7,8,4,2],[4,9,3,2,87],[32,21,54,61,5]])
sample_matrix

array([[ 1,  7,  8,  4,  2],
       [ 4,  9,  3,  2, 87],
       [32, 21, 54, 61,  5]])

In [42]:
sample_matrix[1,2]

3

In [43]:
sample_matrix[2,3]

61

In [44]:
sample_matrix[2,:]

array([32, 21, 54, 61,  5])

In [46]:
sample_matrix[:,(3,1)]

array([[ 4,  7],
       [ 2,  9],
       [61, 21]])

In [47]:
sample_array=np.arange(1,8)
sample_array

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14])

In [49]:
np.max(sample_array)

7

In [50]:
np.min(sample_array)

1

In [51]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131])

In [52]:
np.std(sample_array)

2.0

In [53]:
np.var(sample_array)

4.0

In [54]:
np.square(sample_array)

array([ 1,  4,  9, 16, 25, 36, 49])

In [55]:
np.mean(sample_array)

4.0

In [ ]:
## Import the numpy package under the name "np"

In [ ]:
## Create a null vector of size 10
## Print numbers from 0 to 14
## Create a null vector of size 10 but the fifth value which is 1
## Create a vector with values ranging from 10 to 49
## Reverse a vector (first element becomes last)
## Create a 3x3 matrix with values ranging from 0 to 8
## Create a 3x3 identity matrix
## Create a random vector of size 30 and find the mean value

In [56]:
import numpy as np

In [57]:
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
arr=np.zeros(10)
arr[4]=1

In [61]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [63]:
arr=np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [64]:
arr[::-1]   

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [70]:
arr=np.arange(0,9)


In [72]:
arr1=arr.reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
rand=np.random.rand(30)

In [75]:
np.mean(rand)

0.39159425188255076

In [76]:
### Pandas 
import numpy as np
import pandas as pd


In [77]:
df=pd.read_csv("CardioGoodFitness-1.csv")

In [78]:
df

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
0     TM195   18    Male         14        Single      3        4   29562   
1     TM195   19    Male         15        Single      2        3   31836   
2     TM195   19  Female         14     Partnered      4        3   30699   
3     TM195   19    Male         12        Single      3        3   32973   
4     TM195   20    Male         13     Partnered      4        2   35247   
..      ...  ...     ...        ...           ...    ...      ...     ...   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
0      112  
1       75  
2       66  
3       85  
4       47  
..     ...  
175    200  
176    200  
177    160  
178    120  
179    180  

[180 rows x 9 columns]

In [79]:
df.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47

In [80]:
df.head(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47
5   TM195   20  Female         14     Partnered      3        3   32973     66
6   TM195   21  Female         14     Partnered      3        3   35247     75
7   TM195   21    Male         13        Single      3        3   32973     85
8   TM195   21    Male         15        Single      5        4   35247    141
9   TM195   21  Female         15     Partnered      2        3   37521     85

In [82]:
df.tail(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
170   TM798   31    Male         16     Partnered      6        5   89641   
171   TM798   33  Female         18     Partnered      4        5   95866   
172   TM798   34    Male         16        Single      5        5   92131   
173   TM798   35    Male         16     Partnered      4        5   92131   
174   TM798   38    Male         18     Partnered      5        5  104581   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
170    260  
171    200  
172    150  
173    360  
174    150  
175    200  
176    200  
177    160  
178    120  
179    180

In [85]:
df.sample(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
152   TM798   25  Female         18     Partnered      5        5   61006   
110   TM498   26    Male         16        Single      4        3   51165   
108   TM498   26  Female         16     Partnered      4        3   45480   
64    TM195   35  Female         16     Partnered      3        3   60261   
156   TM798   25    Male         20     Partnered      4        5   74701   
165   TM798   29    Male         18        Single      5        5   52290   
18    TM195   23  Female         16        Single      4        3   38658   
166   TM798   29    Male         14     Partnered      7        5   85906   
136   TM498   40  Female         16        Single      3        3   57987   
38    TM195   26  Female         16        Single      3        3   36384   

     Miles  
152    200  
110    106  
108     85  
64      94  
156    170  
165    180  
18     113  
166    300  
136     85  
38      66

In [86]:
df.dtypes

Product          object
Age               int64
Gender           object
Education         int64
MaritalStatus    object
Usage             int64
Fitness           int64
Income            int64
Miles             int64
dtype: object

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Product        180 non-null    object
 1   Age            180 non-null    int64 
 2   Gender         180 non-null    object
 3   Education      180 non-null    int64 
 4   MaritalStatus  180 non-null    object
 5   Usage          180 non-null    int64 
 6   Fitness        180 non-null    int64 
 7   Income         180 non-null    int64 
 8   Miles          180 non-null    int64 
dtypes: int64(6), object(3)
memory usage: 12.8+ KB


In [88]:
df.describe()

Age   Education       Usage     Fitness         Income  \
count  180.000000  180.000000  180.000000  180.000000     180.000000   
mean    28.788889   15.572222    3.455556    3.311111   53719.577778   
std      6.943498    1.617055    1.084797    0.958869   16506.684226   
min     18.000000   12.000000    2.000000    1.000000   29562.000000   
25%     24.000000   14.000000    3.000000    3.000000   44058.750000   
50%     26.000000   16.000000    3.000000    3.000000   50596.500000   
75%     33.000000   16.000000    4.000000    4.000000   58668.000000   
max     50.000000   21.000000    7.000000    5.000000  104581.000000   

            Miles  
count  180.000000  
mean   103.194444  
std     51.863605  
min     21.000000  
25%     66.000000  
50%     94.000000  
75%    114.750000  
max    360.000000